---
- name: Install Java
  apt:
    name: openjdk-11-jdk-headless
    state: present
    update_cache: yes

- name: Create Kafka user
  user:
    name: kafka
    createhome: true
    shell: /bin/bash

- name: Create Kafka installation directory
  file:
    path: "{{kafka_install_dir}}"
    state: directory
    mode: '0755'

- name: Download Kafka
  get_url:
    url: "https://dlcdn.apache.org/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    dest: "/tmp/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    checksum: "sha512:{{ kafka_checksum }}"

- name: Extract Kafka
  unarchive:
    src: "/tmp/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    dest: "{{ kafka_install_dir }}"
    remote_src: yes
    creates: "{{ kafka_install_dir }}/bin/kafka-server-start.sh"

# Removed redundant steps since unarchive handles directory creation and extraction
# - name: Create Kafka directory
# - name: Move Kafka installation

- name: Create systemd service file for ZooKeeper
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service

- name: Create systemd service file for Kafka
  template:
    src: kafka.service.j2
    dest: /etc/systemd/system/kafka.service

- name: Start and enable ZooKeeper
  systemd:
    name: zookeeper
    state: started
    enabled: yes

- name: Start and enable Kafka
  systemd:
    name: kafka
    state: started
    enabled: yes