bq_dataset_id: "api-project-269968866265.4678823"
table_name: "news_table"
spark_version: "3.4.4"
spark_package: "spark-{{ spark_version }}-bin-without-hadoop"
spark_user: "spark"
spark_group: "spark"
spark_home: "/opt/spark"
